name: Deployment pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Build Frontend
        working-directory: ./blog-client-redux
        run: |
          npm install
          npm run build
      - name: Move Dist to Backend
        run: |
          rm -rf ./blog-server/dist
          mv ./blog-client-redux/dist ./blog-server/dist
      - name: Setup Flyctl
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        working-directory: ./blog-server
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: |
          ls
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: notify of success
        if: ${{ success() && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: sarisia/actions-status-discord@v1
        with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            status: ${{ job.status }}
            content: "Hey<@316911818725392384>"
            title: "Deploy went through!"
            description: "Site deployed view here https://blog-server-wild-glitter-2388.fly.dev/"
            color: 0x0000ff
            url: "https://github.com/sarisia/actions-status-discord"
            username: "GitHub Actions"
      - name: notify of failure
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            status: ${{ job.status }}
            content: "Hey adaone123<@316911818725392384>"
            title: "Something in pipeline failed site, go fix it!"
            description: "Go and fix the issue"
            color: 0x0000ff
            url: "https://github.com/sarisia/actions-status-discord"
            username: "GitHub Actions"

  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0' # Important for tagging actions to see history
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
