name: Ping live site

on:
  schedule:
    - cron: "45 19 * * *"

jobs:
  ping_site:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://blog-server-wild-glitter-2388.fly.dev/
          follow-redirect: false # Optional, defaults to "false"
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
