name: Project Checks

on:
  push:
    branches:
      - main

jobs:
  run-project-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Root Files
        run: ls -R

      - name: Run commands in blog-client-redux
        working-directory: ./blog-client-redux
        run: |
          ls
          npm install --dry-run # Or whatever command you need

      - name: Run commands in other folder
        working-directory: ./blog-server
        run: ls
