name: Project Checks

on:
  push:
    branches:
      - main

jobs:
  run-project-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Root Files
        run: ls -R

      - name: Lint code
        working-directory: ./blog-client-redux
        run: |
          ls
      - name:
        working-directory: ./blog-client-redux
        run: |
          ls
